name: Build and Deploy

on:
  push:
    branches: ['main']

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-website:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\n' | ssh-add -
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-website:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/portfolio-website:latest